spring:
  ### Profile ###
  profiles: development
  ### General Information ###
  application:
      name: example
  ### Security ###
  ssl:
    acceptselfsigned: <true, false>
  ### Cloud Config ###
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8081}

  ### General Information ###
  info:
    app:
      name: Example Service Broker
      description: This is a example Service Broker, demonstrating the purpose of SB development 
      version: 1.1.0

  server:
    port: 8080

  ### Login Information ###
  login:
    username: sample
    password: sample
    role: admin

  ### Persistence ###
  #### MongoDB ####
    data:
      mongodb:
        host: localhost
        port: 27017
        database: service-broker
        username: sb
        password: sb

  ### Deployment ###
  #### Existing MongoDB Server/Cluster ####
  existing:
    endpoint:
      host: <ip>
      port: <port>
      database: <database>
      username: <username>
      password: <password>

  ### Logging ###
  logging:
    file: <file>
    level:
      root: <root>

  ### Service ###
  backend:
    ports:
      default: <port>
    connection:
      timeouts: <timeouts>

  mongodb:
    security:
      key:
        length: <length>

  ### Service Key Generation ###
  #### HAProxy ####
  haproxy:
    uri: <url of the haproxy backend>
    auth:
      token: <authentication token>

  ### Deployment ###
  deployment:
    repo:
      service: <url to the deployment script>
      monit: <url to the monit script>